// Generated by CoffeeScript 1.8.0
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

window.Hand = (function(_super) {
  __extends(Hand, _super);

  function Hand() {
    return Hand.__super__.constructor.apply(this, arguments);
  }

  Hand.prototype.model = Card;

  Hand.prototype.initialize = function(array, deck, isDealer) {
    this.deck = deck;
    this.isDealer = isDealer;
  };

  Hand.prototype.hit = function() {
    var card;
    card = this.deck.pop();
    return this.add(card);
  };

  Hand.prototype.hasAce = function() {
    return this.reduce(function(memo, card) {
      return memo || card.get('value') === 1;
    }, 0);
  };

  Hand.prototype.minScore = function() {
    return this.reduce(function(score, card) {
      return score + (card.get('revealed') ? card.get('value') : 0);
    }, 0);
  };

  Hand.prototype.scores = function() {
    return [this.minScore(), this.minScore() + 10 * this.hasAce()];
  };

  Hand.prototype.stand = function() {
    return this.trigger('reveal', this);
  };

  Hand.prototype.flipFirst = function() {
    console.log('dealer?' + this.isDealer);
    this.at(0).set('revealed', false);
    return this.at(0).flip();
  };

  Hand.prototype.finalScore = function() {
    var max, min, scores;
    scores = this.scores();
    max = Math.max(scores[0], scores[1]);
    min = Math.min(scores[0], scores[1]);
    if (max > 21) {
      return min;
    }
    if (max <= 21) {
      return max;
    }
  };

  return Hand;

})(Backbone.Collection);
